const FOURSQUARE_CLIENT_ID = 'VVPTZCN2VTMV5S2GLEGPTJYRH43EMEVO2SV25KP1BQTWKAHF';
const FOURSQUARE_SECRET = 'MMIXKDWED1QXUPQAVLNH523ADQBZT5Z2IZEJIZV5M0P2PD1O';

export { FOURSQUARE_CLIENT_ID, FOURSQUARE_SECRET };
